decay:
    mother: Lb
    daughter: He3

generator:
    process: SoftQCD
    tune: CRMode2

coalescence:
    radius: 1.e-9 # mm
    momentum_radius: 0.1 # GeV

FONLL:
    filename: inputs/FONLL-Bhadron-dsdpt-sqrts13000-100GeV-50MeVbins.txt

output:
    root: true
    hepmc: false
